# Generated by Django 3.1.3 on 2022-08-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maincont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('sentence', models.TextField()),
                ('word', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
