# Generated by Django 3.1.3 on 2022-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_maincont_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincont',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
