# Generated by Django 3.1.3 on 2022-09-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20220821_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincont',
            name='similar',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincont',
            name='sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maincont',
            name='word',
            field=models.TextField(blank=True),
        ),
    ]
