# Generated by Django 3.1.3 on 2022-09-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20220904_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincont',
            name='similar',
        ),
    ]
